import { ThemeProvider } from '@/lib/contexts/ThemeProvider';
import './global.css';
import { ClerkProvider } from '@clerk/nextjs';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Unitok',
  description: 'Generated by create-nx-workspace',
  icons: {
    icon: [
      {
        url: '/icon-light-32x32.png',
        media: '(prefers-color-scheme: light)',
      },
      {
        url: '/icon-dark-32x32.png',
        media: '(prefers-color-scheme: dark)',
      },
      {
        url: '/icon.svg',
        type: 'image/svg+xml',
      },
    ],
    apple: '/apple-icon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      publishableKey={
        process.env.pk_test_YW1hemVkLWJpc29uLTMxLmNsZXJrLmFjY291bnRzLmRldiQ
      }
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} antialiased bg-background text-foreground`}
        >
          <ThemeProvider>{children}</ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
